obstacle_range: 4.5
raytrace_range: 4.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.4
inflation_radius: 0.5
transform_tolerance: 1
publish_frequency: 0.1
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: Kinect, data_type: LaserScan, topic: /scan, marking: true, clearing: true}