DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.6
  min_vel_x: -0.1 # set to negative, so that DWA planner can execute reverse motion in case of collision or recovery behaviour

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans: 0.6
  min_vel_trans: 0.1

  max_vel_theta: 1.0  
  min_vel_theta: -1.0

  acc_lim_x: 0.4
  acc_lim_y: 0.0
  acc_lim_theta: 0.5

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 10
  vy_samples: 0
  vth_samples: 10
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 16.0
  goal_distance_bias: 12.0
  occdist_scale: 0.015
  forward_point_distance: 0.25
  stop_time_buffer: 0.2
  scaling_speed: 0.20
  max_scaling_factor: 0.2
  meter_scoring: true
  publish_cost_grid: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true