frequency: 30
sensor_timeout: 0.1

two_d_mode: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

publish_tf: true
publish_acceleration: true
publish_odom: true
publish_odometry_tf: true
publish_pose: true
publish_twist: true
publish_filtered_acceleration: false

odom0: /odom

odom0_config: [true,  true,  false,
               false, false, true,
               false, false, false,
               false, false, true,
               false, false, false]

odom0_differential: false
odom0_relative: false
