Agribot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  base_twist_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_twist
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_finger_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_finger
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_finger_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_finger
    pid: {p: 100.0, i: 0.01, d: 10.0}