arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_twist
    - shoulder
    - elbow
    - wrist
  gains:
    base_twist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - wrist
    - left_finger
    - right_finger
  gains:
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1